
services:

  # ------- nginx-proxy (reverse‑proxy) -------
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy_certs:/etc/nginx/certs:ro
      - proxy_vhost.d:/etc/nginx/vhost.d:rw        # <— comparte vhost.d
      - proxy_html:/usr/share/nginx/html:rw       # <— comparte html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  # ------- companion que gestiona certificados -------
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - proxy_certs:/etc/nginx/certs
      - proxy_vhost.d:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme_sh:/etc/acme.sh
    networks:
      - proxy

networks:
  proxy:
    name: proxy     # aquí forzamos el nombre real "proxy"

volumes:
  proxy_certs:
  proxy_vhost.d:
  proxy_html:
  acme_sh: